import { createPrefabComponent } from "@/helpers/prefab";

export const Common = {
    Panel: createPrefabComponent("Common.ui", "Panel", "Group"),
    TitleLabel: createPrefabComponent("Common.ui", "TitleLabel", "Label"),
    TextButton: createPrefabComponent("Common.ui", "TextButton", "TextButton"),
    Button: createPrefabComponent("Common.ui", "Button", "Button"),
    CancelTextButton: createPrefabComponent("Common.ui", "CancelTextButton", "TextButton"),
    CancelButton: createPrefabComponent("Common.ui", "CancelButton", "Button"),
    SmallSecondaryTextButton: createPrefabComponent("Common.ui", "SmallSecondaryTextButton", "TextButton"),
    SmallTertiaryTextButton: createPrefabComponent("Common.ui", "SmallTertiaryTextButton", "TextButton"),
    SecondaryTextButton: createPrefabComponent("Common.ui", "SecondaryTextButton", "TextButton"),
    SecondaryButton: createPrefabComponent("Common.ui", "SecondaryButton", "Button"),
    TertiaryTextButton: createPrefabComponent("Common.ui", "TertiaryTextButton", "TextButton"),
    TertiaryButton: createPrefabComponent("Common.ui", "TertiaryButton", "Button"),
    CloseButton: createPrefabComponent("Common.ui", "CloseButton", "Button"),
    CheckBox: createPrefabComponent("Common.ui", "CheckBox", "CheckBox"),
    CheckBoxWithLabel: createPrefabComponent("Common.ui", "CheckBoxWithLabel", "Group"),
    TextField: createPrefabComponent("Common.ui", "TextField", "TextField"),
    NumberField: createPrefabComponent("Common.ui", "NumberField", "NumberField"),
    DropdownBox: createPrefabComponent("Common.ui", "DropdownBox", "DropdownBox"),
    ContentSeparator: createPrefabComponent("Common.ui", "ContentSeparator", "Group"),
    DefaultSpinner: createPrefabComponent("Common.ui", "DefaultSpinner", "Sprite"),
    ActionButtonContainer: createPrefabComponent("Common.ui", "ActionButtonContainer", "Group"),
    ActionButtonSeparator: createPrefabComponent("Common.ui", "ActionButtonSeparator", "Group"),
    VerticalActionButtonSeparator: createPrefabComponent("Common.ui", "VerticalActionButtonSeparator", "Group"),
    Subtitle: createPrefabComponent("Common.ui", "Subtitle", "Label"),
    Title: createPrefabComponent("Common.ui", "Title", "Label"),
    HeaderSearch: createPrefabComponent("Common.ui", "HeaderSearch", "Group"),
    HeaderTextButton: createPrefabComponent("Common.ui", "HeaderTextButton", "TextButton"),
    HeaderSeparator: createPrefabComponent("Common.ui", "HeaderSeparator", "Group"),
    PanelTitle: createPrefabComponent("Common.ui", "PanelTitle", "Group"),
    VerticalSeparator: createPrefabComponent("Common.ui", "VerticalSeparator", "Group"),
    PanelSeparatorFancy: createPrefabComponent("Common.ui", "PanelSeparatorFancy", "Group"),
    Container: createPrefabComponent("Common.ui", "Container", "Group"),
    DecoratedContainer: createPrefabComponent("Common.ui", "DecoratedContainer", "Group"),
    PageOverlay: createPrefabComponent("Common.ui", "PageOverlay", "Group"),
    BackButton: createPrefabComponent("Common.ui", "BackButton", "Group"),
}
