import { createPrefabComponent } from "@/helpers/prefab";

const COMMON_PATH = "../Common.ui"

export const Common = {
    Panel: createPrefabComponent(COMMON_PATH, "Panel", "Group"),
    TitleLabel: createPrefabComponent(COMMON_PATH, "TitleLabel", "Label"),
    TextButton: createPrefabComponent(COMMON_PATH, "TextButton", "TextButton"),
    Button: createPrefabComponent(COMMON_PATH, "Button", "Button"),
    CancelTextButton: createPrefabComponent(COMMON_PATH, "CancelTextButton", "TextButton"),
    CancelButton: createPrefabComponent(COMMON_PATH, "CancelButton", "Button"),
    SmallSecondaryTextButton: createPrefabComponent(COMMON_PATH, "SmallSecondaryTextButton", "TextButton"),
    SmallTertiaryTextButton: createPrefabComponent(COMMON_PATH, "SmallTertiaryTextButton", "TextButton"),
    SecondaryTextButton: createPrefabComponent(COMMON_PATH, "SecondaryTextButton", "TextButton"),
    SecondaryButton: createPrefabComponent(COMMON_PATH, "SecondaryButton", "Button"),
    TertiaryTextButton: createPrefabComponent(COMMON_PATH, "TertiaryTextButton", "TextButton"),
    TertiaryButton: createPrefabComponent(COMMON_PATH, "TertiaryButton", "Button"),
    CloseButton: createPrefabComponent(COMMON_PATH, "CloseButton", "Button"),
    CheckBox: createPrefabComponent(COMMON_PATH, "CheckBox", "CheckBox"),
    CheckBoxWithLabel: createPrefabComponent(COMMON_PATH, "CheckBoxWithLabel", "Group"),
    TextField: createPrefabComponent(COMMON_PATH, "TextField", "TextField"),
    NumberField: createPrefabComponent(COMMON_PATH, "NumberField", "NumberField"),
    DropdownBox: createPrefabComponent(COMMON_PATH, "DropdownBox", "DropdownBox"),
    ContentSeparator: createPrefabComponent(COMMON_PATH, "ContentSeparator", "Group"),
    DefaultSpinner: createPrefabComponent(COMMON_PATH, "DefaultSpinner", "Sprite"),
    ActionButtonContainer: createPrefabComponent(COMMON_PATH, "ActionButtonContainer", "Group"),
    ActionButtonSeparator: createPrefabComponent(COMMON_PATH, "ActionButtonSeparator", "Group"),
    VerticalActionButtonSeparator: createPrefabComponent(COMMON_PATH, "VerticalActionButtonSeparator", "Group"),
    Subtitle: createPrefabComponent(COMMON_PATH, "Subtitle", "Label"),
    Title: createPrefabComponent(COMMON_PATH, "Title", "Label"),
    HeaderSearch: createPrefabComponent(COMMON_PATH, "HeaderSearch", "Group"),
    HeaderTextButton: createPrefabComponent(COMMON_PATH, "HeaderTextButton", "TextButton"),
    HeaderSeparator: createPrefabComponent(COMMON_PATH, "HeaderSeparator", "Group"),
    PanelTitle: createPrefabComponent(COMMON_PATH, "PanelTitle", "Group"),
    VerticalSeparator: createPrefabComponent(COMMON_PATH, "VerticalSeparator", "Group"),
    PanelSeparatorFancy: createPrefabComponent(COMMON_PATH, "PanelSeparatorFancy", "Group"),
    Container: createPrefabComponent(COMMON_PATH, "Container", "Group"),
    DecoratedContainer: createPrefabComponent(COMMON_PATH, "DecoratedContainer", "Group"),
    PageOverlay: createPrefabComponent(COMMON_PATH, "PageOverlay", "Group"),
    BackButton: createPrefabComponent(COMMON_PATH, "BackButton", "Group"),
}
